export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const RETRIEVE_PRODUCT = "RETRIEVE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_ALL_PRODUCT = "DELETE_ALL_PRODUCT";

export const CREATE_CATEGORY = "CREATE_CATEGORY";
export const RETRIEVE_CATEGORY = "RETRIEVE_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";
export const DELETE_ALL_CATEGORY = "DELETE_ALL_CATEGORY";

export const CREATE_CART = "CREATE_CART";
export const RETRIEVE_CART = "RETRIEVE_CART";
export const UPDATE_CART = "UPDATE_CART";
export const DELETE_CART = "DELETE_CART";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";